import * as fs from "node:fs/promises";
import * as path from "node:path";
import { type IntentConfig } from "@intent/schemas";
import { type Result, ok, err, intentError } from "./result.js";
import { writeConfig, isInitialized } from "./config.js";
import { intentDir, plansDir, decisionsDir, systemsDir, constraintsDir, linksDir } from "./paths.js";

export interface InitOptions {
  project: string;
  force?: boolean;
}

export async function initIntent(root: string, options: InitOptions): Promise<Result<void>> {
  if (!options.force && await isInitialized(root)) {
    return err(intentError("ALREADY_INITIALIZED", ".intent/ already exists. Use --force to reinitialize."));
  }

  const dirs = [
    intentDir(root),
    plansDir(root),
    decisionsDir(root),
    systemsDir(root),
    constraintsDir(root),
    linksDir(root),
  ];

  try {
    for (const dir of dirs) {
      await fs.mkdir(dir, { recursive: true });
    }
  } catch (cause) {
    return err(intentError("WRITE_ERROR", "Failed to create .intent/ directories", cause));
  }

  const config: IntentConfig = {
    version: "1",
    project: options.project,
    systems: [],
    created: new Date().toISOString(),
  };

  const writeResult = await writeConfig(root, config);
  if (!writeResult.ok) return writeResult;

  await writeGitignore(root);

  return ok(undefined);
}

async function writeGitignore(root: string): Promise<void> {
  const gitignorePath = path.join(intentDir(root), ".gitignore");
  const content = "# Auto-generated index files — regenerated by 'intent link'\nlinks/\n";
  try {
    await fs.writeFile(gitignorePath, content, "utf8");
  } catch {
    // non-fatal
  }
}
